In [112]:
import torch
import numpy as np
import torch.nn as nn
from  collections import OrderedDict

In [113]:
pixel=torch.randn(3,32,32)

In [114]:
pixel

tensor([[[-0.1747,  0.4304,  1.4762,  ..., -1.3892,  0.8853, -0.5622],
         [-0.2421, -0.5918,  1.4650,  ..., -1.2095,  0.0581, -1.0142],
         [ 0.3152, -0.2146,  0.4101,  ..., -0.7601,  0.7225, -0.9411],
         ...,
         [-0.2815, -0.0444,  0.8454,  ..., -0.3357, -0.1597, -0.1768],
         [ 0.5046,  0.2721, -0.6173,  ..., -0.6036, -1.4626,  0.2129],
         [ 0.1880,  0.4228,  1.0938,  ..., -2.6051,  0.4965, -0.6882]],

        [[-0.0268,  0.9074,  0.0611,  ...,  1.0009, -1.2261,  0.7830],
         [ 1.2390, -0.8913, -0.9464,  ..., -0.1622, -1.0847, -0.7451],
         [ 0.5499,  0.4509, -1.2752,  ...,  0.5028,  0.3228,  0.3901],
         ...,
         [ 0.5287, -1.5825,  0.6325,  ..., -1.6893, -0.1282,  0.7209],
         [ 0.9355,  1.1305,  2.0457,  ..., -0.3376,  0.5888, -1.9463],
         [-0.5883,  1.8352, -0.9527,  ...,  0.9737, -0.8998,  0.4278]],

        [[ 0.1977,  0.5490,  0.5267,  ..., -0.9757, -1.3130,  1.0234],
         [ 0.6318,  0.0420,  0.2640,  ..., -1

In [115]:
result_p=OrderedDict()
result_s=OrderedDict()



In [116]:
def pool2d(X, pool_size, mode='max'):
    X = X.float()
    p_h, p_w = pool_size
    Y = torch.zeros(X.shape[0],X.shape[1] - p_h + 1, X.shape[2] - p_w + 1)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            for k in range(Y.shape[2]):
                if mode == 'max':
                    Y[i, j, k] = X[i,j: j + p_h, k: k + p_w].max()
                elif mode == 'mean':
                    Y[i, j, k] = X[i,j: j + p_h, k: k + p_w].mean()       
    return Y

### 1.Maxpooling

In [117]:

layer1=torch.nn.MaxPool2d(kernel_size=2,stride=1,
                   padding=0,dilation=1,return_indices=False,ceil_mode=False)
p_maxp=layer1(pixel)

In [118]:
p_maxp[0]

tensor([[ 0.4304,  1.4762,  1.4762,  0.3512,  1.0790,  1.0790,  0.5874,  1.9505,
          1.9505,  0.8691,  0.1246,  1.2153,  1.2153,  1.3114,  1.3114,  0.9992,
          1.5760,  1.5760,  2.0017,  2.0017,  0.9464,  1.2448,  1.4489,  1.4489,
         -1.2334,  0.4110,  1.7083,  1.7083,  1.4271,  0.8853,  0.8853],
        [ 0.3152,  1.4650,  1.4650,  0.6579,  0.6579, -0.5264, -0.2933,  1.9505,
          1.9505,  1.0570,  0.1246,  1.2153,  1.2153,  1.3114,  1.3114,  1.2117,
          1.2117,  1.1489,  2.0017,  2.0017,  0.9464,  0.4437,  1.4489,  1.4489,
          1.3510,  1.3510,  1.2986,  1.4271,  1.4271,  0.7225,  0.7225],
        [ 0.6206,  0.6206,  0.4101,  0.6579,  0.6579, -0.0407, -0.2933, -0.2933,
          1.0570,  1.4595,  1.4595,  0.0422,  0.7197,  0.9920,  1.0413,  1.2117,
          1.8063,  1.8063,  1.6325,  1.6325,  0.4437,  1.1951,  1.1951, -0.1255,
          1.3510,  1.3510,  1.2986,  0.2732,  0.7890,  0.7890,  0.7225],
        [ 1.5666,  1.5666,  0.3059,  0.5836,  0.5836

In [119]:
result_p["MaxPool2d"]=p_maxp.numpy()

In [120]:
s_maxp=pool2d(pixel,(2,2),'max')
s_maxp[0]

tensor([[ 0.4304,  1.4762,  1.4762,  0.3512,  1.0790,  1.0790,  0.5874,  1.9505,
          1.9505,  0.8691,  0.1246,  1.2153,  1.2153,  1.3114,  1.3114,  0.9992,
          1.5760,  1.5760,  2.0017,  2.0017,  0.9464,  1.2448,  1.4489,  1.4489,
         -1.2334,  0.4110,  1.7083,  1.7083,  1.4271,  0.8853,  0.8853],
        [ 0.3152,  1.4650,  1.4650,  0.6579,  0.6579, -0.5264, -0.2933,  1.9505,
          1.9505,  1.0570,  0.1246,  1.2153,  1.2153,  1.3114,  1.3114,  1.2117,
          1.2117,  1.1489,  2.0017,  2.0017,  0.9464,  0.4437,  1.4489,  1.4489,
          1.3510,  1.3510,  1.2986,  1.4271,  1.4271,  0.7225,  0.7225],
        [ 0.6206,  0.6206,  0.4101,  0.6579,  0.6579, -0.0407, -0.2933, -0.2933,
          1.0570,  1.4595,  1.4595,  0.0422,  0.7197,  0.9920,  1.0413,  1.2117,
          1.8063,  1.8063,  1.6325,  1.6325,  0.4437,  1.1951,  1.1951, -0.1255,
          1.3510,  1.3510,  1.2986,  0.2732,  0.7890,  0.7890,  0.7225],
        [ 1.5666,  1.5666,  0.3059,  0.5836,  0.5836

In [121]:
result_s["MaxPool2d"]=s_maxp.numpy()
# save_file(result_s,path_s)

### 2. Avgpooling

In [122]:
layer1=torch.nn.AvgPool2d(kernel_size=2,stride=1,
                   padding=0,ceil_mode=False,count_include_pad=True
                          ,divisor_override=None)
p_avgp=layer1(pixel)


In [123]:
p_avgp

tensor([[[-1.4454e-01,  6.9497e-01,  3.5424e-01,  ..., -2.6325e-01,
          -4.1384e-01, -1.5826e-01],
         [-1.8331e-01,  2.6718e-01, -1.2643e-01,  ..., -6.7339e-02,
          -2.9726e-01, -2.9369e-01],
         [-1.8256e-01,  2.8050e-01, -2.4060e-01,  ..., -6.7880e-02,
          -7.2154e-02, -7.5195e-01],
         ...,
         [-2.2339e-01,  3.9281e-01,  2.1644e-01,  ..., -1.3063e-03,
           1.0889e-01,  2.4555e-01],
         [ 1.1269e-01,  1.1395e-01,  2.5710e-01,  ..., -2.9001e-01,
          -6.4041e-01, -3.9656e-01],
         [ 3.4687e-01,  2.9286e-01,  3.0088e-01,  ..., -8.4892e-01,
          -1.0437e+00, -3.6033e-01]],

        [[ 3.0704e-01, -2.1732e-01, -5.6947e-01,  ..., -5.2094e-01,
          -3.6802e-01, -5.6824e-01],
         [ 3.3711e-01, -6.6549e-01, -6.4462e-01,  ..., -2.5563e-01,
          -1.0532e-01, -2.7921e-01],
         [ 3.1975e-01, -4.4072e-01, -6.8165e-01,  ...,  2.1683e-01,
           2.8601e-01,  6.8703e-01],
         ...,
         [-1.5099e-01, -6

In [124]:
result_p["AvgPool2d"]=p_avgp.numpy()

In [125]:
s_avgp=pool2d(pixel,(2,2),'mean')
s_avgp

tensor([[[-1.4454e-01,  6.9497e-01,  3.5424e-01,  ..., -2.6325e-01,
          -4.1384e-01, -1.5826e-01],
         [-1.8331e-01,  2.6718e-01, -1.2643e-01,  ..., -6.7339e-02,
          -2.9726e-01, -2.9369e-01],
         [-1.8256e-01,  2.8050e-01, -2.4060e-01,  ..., -6.7880e-02,
          -7.2154e-02, -7.5195e-01],
         ...,
         [-2.2339e-01,  3.9281e-01,  2.1644e-01,  ..., -1.3063e-03,
           1.0889e-01,  2.4555e-01],
         [ 1.1269e-01,  1.1395e-01,  2.5710e-01,  ..., -2.9001e-01,
          -6.4041e-01, -3.9656e-01],
         [ 3.4687e-01,  2.9286e-01,  3.0088e-01,  ..., -8.4892e-01,
          -1.0437e+00, -3.6033e-01]],

        [[ 3.0704e-01, -2.1732e-01, -5.6947e-01,  ..., -5.2094e-01,
          -3.6802e-01, -5.6824e-01],
         [ 3.3711e-01, -6.6549e-01, -6.4462e-01,  ..., -2.5563e-01,
          -1.0532e-01, -2.7921e-01],
         [ 3.1975e-01, -4.4072e-01, -6.8165e-01,  ...,  2.1683e-01,
           2.8601e-01,  6.8703e-01],
         ...,
         [-1.5099e-01, -6

In [126]:
result_s["AvgPool2d"]=s_avgp.numpy()
# save_file(result_p,path_p)

In [127]:
# save_file(result_s,path_s)

### 3 Conv2d

In [128]:
def pool2d_one(X, weight,bias,channel):
    X = X.float()
    p_h=weight.shape[2]
    p_w=weight.shape[3]
    Y = torch.zeros(1,X.shape[1] - p_h + 1, X.shape[2] - p_w + 1)
    for i in range(X.shape[0]):
        for j in range(Y.shape[1]):
            for k in range(Y.shape[2]):
                    Y[0, j, k] += (X[i,j: j + p_h, k: k + p_w]*weight[channel][i]).sum()
    Y=Y+bias[channel]
    return Y

def poo2d_multi(X, weight,bias,out_channels):
    result=[]
    for i in range(out_channels):
        Y=pool2d_one(X, weight,bias,i)
        result.append(Y)
        
    return torch.stack(result,dim=1)

In [129]:
layer1=torch.nn.Conv2d(in_channels=3,out_channels=6,kernel_size=3,stride=1,
                     padding=0,dilation=1,groups=1,bias=True,padding_mode='zeros')
p_cp=layer1(pixel.view(-1,3,32,32))


In [130]:
p_cp

tensor([[[[-0.5458, -0.4710,  0.4342,  ...,  1.0208, -0.3421, -0.3785],
          [-0.2458,  0.0379, -0.8036,  ...,  0.6959, -0.1947, -0.3407],
          [-0.6294,  0.2846, -0.2545,  ...,  0.0417, -0.0101,  0.2260],
          ...,
          [ 0.5918,  0.7689, -0.3448,  ...,  0.3013, -0.5811, -0.0245],
          [-0.7965, -0.1868,  1.3834,  ..., -0.7110, -0.7230,  0.1167],
          [ 0.9844,  0.1188,  1.1551,  ..., -0.7347,  0.0740, -0.3081]],

         [[ 0.0311,  0.0201, -0.5966,  ...,  0.3616,  0.1255,  0.2415],
          [-0.1119,  0.0524,  0.6568,  ..., -0.2503,  0.4387, -0.4318],
          [ 0.1058,  0.5740,  0.3298,  ...,  0.0967, -0.3062, -0.4915],
          ...,
          [-0.3841,  0.7867,  0.2492,  ...,  0.7414,  0.6102, -0.2049],
          [ 0.9841, -0.1017,  0.0823,  ...,  0.4373,  0.8584, -0.7321],
          [-0.2244, -0.3301,  0.2463,  ...,  0.5598, -0.2096,  0.4870]],

         [[ 0.7275,  0.4822,  1.0895,  ..., -0.4518,  0.1820, -1.3261],
          [-0.0304,  0.1049,  

In [131]:
x=p_cp.squeeze()
x.shape
result_p["conv2d_3"]=x.detach().numpy()

In [132]:
layer1.weight.shape

torch.Size([6, 3, 3, 3])

In [133]:
y=poo2d_multi(pixel,layer1.weight,layer1.bias,6)
y=y.squeeze()
result_s["conv2d_3"]=y.detach().numpy()

In [134]:
y

tensor([[[-0.5458, -0.4710,  0.4342,  ...,  1.0208, -0.3421, -0.3785],
         [-0.2458,  0.0379, -0.8036,  ...,  0.6959, -0.1947, -0.3407],
         [-0.6294,  0.2846, -0.2545,  ...,  0.0417, -0.0101,  0.2260],
         ...,
         [ 0.5918,  0.7689, -0.3448,  ...,  0.3013, -0.5811, -0.0245],
         [-0.7965, -0.1868,  1.3834,  ..., -0.7110, -0.7230,  0.1167],
         [ 0.9844,  0.1188,  1.1551,  ..., -0.7347,  0.0740, -0.3081]],

        [[ 0.0311,  0.0201, -0.5966,  ...,  0.3616,  0.1255,  0.2415],
         [-0.1119,  0.0524,  0.6568,  ..., -0.2503,  0.4387, -0.4318],
         [ 0.1058,  0.5740,  0.3298,  ...,  0.0967, -0.3062, -0.4915],
         ...,
         [-0.3841,  0.7867,  0.2492,  ...,  0.7414,  0.6102, -0.2049],
         [ 0.9841, -0.1017,  0.0823,  ...,  0.4373,  0.8584, -0.7321],
         [-0.2244, -0.3301,  0.2463,  ...,  0.5598, -0.2096,  0.4870]],

        [[ 0.7275,  0.4822,  1.0895,  ..., -0.4518,  0.1820, -1.3261],
         [-0.0304,  0.1049,  0.4996,  ..., -0

In [135]:
# save_file(result_s,path_s)

### 4 Conv2d

In [136]:
def pool2d_one(X, weight,bias,channel,stride,dilation):
    X = X.float()
    p_h=weight.shape[2]
    p_w=weight.shape[3]
    Y = torch.zeros(1,(X.shape[1] - dilation*(p_h-1)-1)//stride + 1,
                    (X.shape[2] - dilation*(p_w-1)-1)//stride + 1)
    for i in range(X.shape[0]):
        for j in range(Y.shape[1],):
            for k in range(Y.shape[2]):

                candidate=X[i,j*stride: j*stride + p_h*dilation,
                                     k*stride: k*stride + p_w*dilation]
#                 print(candidate.shape)
                candidate_=torch.zeros(p_h,p_w)
                for m in range(p_h):
                    for n in range(p_w):
#                         print(n)
                        candidate_[m,n]=candidate[m*dilation,n*dilation]
                
                Y[0, j, k] += (candidate_*weight[channel][i]).sum()
    Y=Y+bias[channel]
    return Y

def poo2d_multi(X, weight,bias,out_channels,stride,dilation):
    result=[]
    for i in range(out_channels):
        Y=pool2d_one(X, weight,bias,i,stride,dilation)
        result.append(Y)
        
    return torch.stack(result,dim=1)

In [137]:
layer1=torch.nn.Conv2d(in_channels=3,out_channels=6,kernel_size=5,stride=2,
                     padding=0,dilation=2,groups=1,bias=True,padding_mode='zeros')
p_cp=layer1(pixel.view(-1,3,32,32))


In [138]:
p_cp

tensor([[[[ 9.8082e-01,  3.6878e-01, -2.6793e-01,  1.0501e+00, -6.4759e-03,
            1.0300e+00, -8.9634e-01,  1.6020e-01, -3.0152e-01,  7.4518e-01,
           -3.5470e-01,  7.9832e-02],
          [ 2.3667e-02,  3.0046e-01,  1.6391e-01, -1.3109e-02,  5.4755e-02,
           -2.5249e-01, -3.0247e-01, -2.7489e-02,  1.0377e+00,  2.4424e-01,
           -6.3036e-03,  6.7403e-01],
          [-1.0037e+00,  9.9335e-02,  9.5894e-02, -1.0560e+00,  5.4179e-01,
            8.6613e-02, -4.5374e-02, -1.5539e+00, -5.3521e-01, -5.1221e-01,
           -4.3805e-01,  3.5207e-01],
          [-1.6790e-01,  5.1332e-01,  9.1573e-02,  1.4200e-01, -6.8670e-01,
           -7.9863e-01, -1.7759e-01,  3.3696e-01,  4.0907e-01,  5.4606e-02,
           -2.9358e-01, -5.3687e-01],
          [-3.9614e-01, -9.8938e-01, -1.3624e+00,  8.6553e-01,  7.4286e-01,
           -8.5557e-01, -4.8376e-01, -2.4004e-01, -1.9502e-01, -5.1689e-01,
            1.7178e-01, -1.4426e-01],
          [ 8.3745e-01,  1.1841e+00, -7.2013e-01, 

In [139]:
s_cp=poo2d_multi(pixel,layer1.weight,layer1.bias,6,2,2)
s_cp

tensor([[[[ 9.8082e-01,  3.6878e-01, -2.6793e-01,  1.0501e+00, -6.4759e-03,
            1.0300e+00, -8.9634e-01,  1.6020e-01, -3.0152e-01,  7.4518e-01,
           -3.5470e-01,  7.9832e-02],
          [ 2.3667e-02,  3.0046e-01,  1.6391e-01, -1.3109e-02,  5.4755e-02,
           -2.5249e-01, -3.0247e-01, -2.7489e-02,  1.0377e+00,  2.4424e-01,
           -6.3035e-03,  6.7403e-01],
          [-1.0037e+00,  9.9335e-02,  9.5894e-02, -1.0560e+00,  5.4179e-01,
            8.6613e-02, -4.5374e-02, -1.5539e+00, -5.3521e-01, -5.1221e-01,
           -4.3805e-01,  3.5207e-01],
          [-1.6790e-01,  5.1332e-01,  9.1573e-02,  1.4200e-01, -6.8670e-01,
           -7.9863e-01, -1.7759e-01,  3.3696e-01,  4.0907e-01,  5.4606e-02,
           -2.9358e-01, -5.3687e-01],
          [-3.9614e-01, -9.8938e-01, -1.3624e+00,  8.6553e-01,  7.4286e-01,
           -8.5557e-01, -4.8376e-01, -2.4004e-01, -1.9502e-01, -5.1689e-01,
            1.7178e-01, -1.4426e-01],
          [ 8.3745e-01,  1.1841e+00, -7.2013e-01, 

In [140]:
result_p["conv2d_4"]=p_cp.squeeze().detach().numpy()

In [141]:
result_p["conv2d_4"].shape

(6, 12, 12)

In [142]:
result_s["conv2d_4"]=s_cp.squeeze().detach().numpy()

In [143]:
# save_file(result_s,path_s)

### 5 convtranspose

In [144]:
def pool2d_one(X,weight,bias,channel):
    h= weight.shape[2]
    w=weight.shape[3]
    Y = torch.zeros((1,X.shape[1] + h - 1, X.shape[2] + w - 1))
#     print(Y.shape)
    for k in range(X.shape[0]):
        for i in range(X.shape[1]):
            for j in range(X.shape[2]):
                Y[0,i:i + h, j:j + w] += X[k,i, j] * weight[k][channel]
    Y+=bias[channel]
    return Y
def poo2d_multi(X, weight,bias,out_channels):
    result=[]
    for i in range(out_channels):
#         print(i)
        Y=pool2d_one(X, weight,bias,i)
#         print(Y.shape)
        result.append(Y)
        
    return torch.stack(result,dim=1)

In [145]:
# import tensorflow as tf

In [146]:
# tf.nn.conv2d_transpose()

In [147]:
layer1=torch.nn.ConvTranspose2d(in_channels=3, out_channels=4,kernel_size=3,
                         stride=1, padding=0, output_padding=0,groups=1, bias=True, dilation=1, padding_mode='zeros')
p_ct=layer1(pixel.view(-1,3,32,32))

In [148]:
p_ct

tensor([[[[ 1.7476e-01,  1.9959e-02, -1.1368e-01,  ...,  3.9062e-02,
            2.8151e-01,  1.0834e-02],
          [ 2.2674e-02,  1.7135e-01, -1.1242e-01,  ...,  1.7615e-01,
            3.8917e-01,  2.9778e-01],
          [ 3.1494e-02,  3.1717e-01,  3.8101e-01,  ...,  3.2933e-01,
           -6.1160e-02, -1.2382e-01],
          ...,
          [ 2.0219e-01, -3.4157e-01,  1.3685e-01,  ..., -4.7228e-01,
            6.2859e-01,  1.0193e-01],
          [ 2.6452e-01,  4.1864e-01,  3.0200e-02,  ..., -6.3282e-03,
           -6.5401e-02, -2.7616e-01],
          [ 1.1396e-01,  3.7140e-01,  4.8424e-02,  ...,  1.5040e-01,
           -9.9728e-02,  2.7189e-01]],

         [[ 1.1491e-01,  1.0539e-01,  2.4672e-01,  ..., -4.8219e-02,
            4.3166e-01,  7.6871e-02],
          [-6.5340e-02,  2.2588e-01,  6.6976e-01,  ..., -4.1388e-01,
            5.3932e-02,  3.3415e-01],
          [-2.2996e-01, -1.3571e-01,  6.6872e-01,  ..., -5.9541e-01,
            2.1587e-01, -9.1048e-02],
          ...,
     

In [149]:
p_conv_trans=poo2d_multi(pixel, layer1.weight,layer1.bias,4)
p_conv_trans

tensor([[[[ 1.7476e-01,  1.9959e-02, -1.1368e-01,  ...,  3.9062e-02,
            2.8151e-01,  1.0834e-02],
          [ 2.2674e-02,  1.7135e-01, -1.1242e-01,  ...,  1.7615e-01,
            3.8917e-01,  2.9778e-01],
          [ 3.1494e-02,  3.1717e-01,  3.8101e-01,  ...,  3.2933e-01,
           -6.1160e-02, -1.2382e-01],
          ...,
          [ 2.0219e-01, -3.4157e-01,  1.3685e-01,  ..., -4.7228e-01,
            6.2859e-01,  1.0193e-01],
          [ 2.6452e-01,  4.1864e-01,  3.0200e-02,  ..., -6.3282e-03,
           -6.5401e-02, -2.7616e-01],
          [ 1.1396e-01,  3.7140e-01,  4.8424e-02,  ...,  1.5040e-01,
           -9.9728e-02,  2.7189e-01]],

         [[ 1.1491e-01,  1.0539e-01,  2.4672e-01,  ..., -4.8219e-02,
            4.3166e-01,  7.6871e-02],
          [-6.5339e-02,  2.2588e-01,  6.6976e-01,  ..., -4.1388e-01,
            5.3932e-02,  3.3415e-01],
          [-2.2996e-01, -1.3571e-01,  6.6872e-01,  ..., -5.9541e-01,
            2.1587e-01, -9.1048e-02],
          ...,
     

In [150]:
p_ct.squeeze()

tensor([[[ 1.7476e-01,  1.9959e-02, -1.1368e-01,  ...,  3.9062e-02,
           2.8151e-01,  1.0834e-02],
         [ 2.2674e-02,  1.7135e-01, -1.1242e-01,  ...,  1.7615e-01,
           3.8917e-01,  2.9778e-01],
         [ 3.1494e-02,  3.1717e-01,  3.8101e-01,  ...,  3.2933e-01,
          -6.1160e-02, -1.2382e-01],
         ...,
         [ 2.0219e-01, -3.4157e-01,  1.3685e-01,  ..., -4.7228e-01,
           6.2859e-01,  1.0193e-01],
         [ 2.6452e-01,  4.1864e-01,  3.0200e-02,  ..., -6.3282e-03,
          -6.5401e-02, -2.7616e-01],
         [ 1.1396e-01,  3.7140e-01,  4.8424e-02,  ...,  1.5040e-01,
          -9.9728e-02,  2.7189e-01]],

        [[ 1.1491e-01,  1.0539e-01,  2.4672e-01,  ..., -4.8219e-02,
           4.3166e-01,  7.6871e-02],
         [-6.5340e-02,  2.2588e-01,  6.6976e-01,  ..., -4.1388e-01,
           5.3932e-02,  3.3415e-01],
         [-2.2996e-01, -1.3571e-01,  6.6872e-01,  ..., -5.9541e-01,
           2.1587e-01, -9.1048e-02],
         ...,
         [-7.2648e-04,  2

In [151]:
result_p["transpose_2d"]=p_ct.squeeze().detach().numpy()

In [152]:
result_p["transpose_2d"]

array([[[ 1.74762174e-01,  1.99594051e-02, -1.13675550e-01, ...,
          3.90618593e-02,  2.81507820e-01,  1.08344406e-02],
        [ 2.26736516e-02,  1.71354964e-01, -1.12423435e-01, ...,
          1.76145032e-01,  3.89171720e-01,  2.97775209e-01],
        [ 3.14942449e-02,  3.17172945e-01,  3.81012857e-01, ...,
          3.29328716e-01, -6.11596704e-02, -1.23822436e-01],
        ...,
        [ 2.02185452e-01, -3.41567278e-01,  1.36852130e-01, ...,
         -4.72276449e-01,  6.28588676e-01,  1.01928577e-01],
        [ 2.64517725e-01,  4.18635368e-01,  3.01995575e-02, ...,
         -6.32818043e-03, -6.54007643e-02, -2.76157320e-01],
        [ 1.13963850e-01,  3.71399105e-01,  4.84241322e-02, ...,
          1.50395632e-01, -9.97278243e-02,  2.71887302e-01]],

       [[ 1.14909574e-01,  1.05385959e-01,  2.46716768e-01, ...,
         -4.82187420e-02,  4.31664705e-01,  7.68714771e-02],
        [-6.53395057e-02,  2.25880206e-01,  6.69758201e-01, ...,
         -4.13879871e-01,  5.39322942e

In [153]:
result_s["transpose_2d"]=p_conv_trans.squeeze().detach().numpy()

In [154]:
result_s["transpose_2d"]

array([[[ 1.74762174e-01,  1.99594051e-02, -1.13675520e-01, ...,
          3.90618593e-02,  2.81507790e-01,  1.08344406e-02],
        [ 2.26736367e-02,  1.71354964e-01, -1.12423465e-01, ...,
          1.76145047e-01,  3.89171720e-01,  2.97775209e-01],
        [ 3.14942598e-02,  3.17172945e-01,  3.81012887e-01, ...,
          3.29328686e-01, -6.11596704e-02, -1.23822436e-01],
        ...,
        [ 2.02185452e-01, -3.41567278e-01,  1.36852115e-01, ...,
         -4.72276449e-01,  6.28588617e-01,  1.01928577e-01],
        [ 2.64517725e-01,  4.18635368e-01,  3.01995575e-02, ...,
         -6.32818043e-03, -6.54007643e-02, -2.76157320e-01],
        [ 1.13963850e-01,  3.71399105e-01,  4.84241322e-02, ...,
          1.50395632e-01, -9.97278243e-02,  2.71887302e-01]],

       [[ 1.14909574e-01,  1.05385959e-01,  2.46716768e-01, ...,
         -4.82187718e-02,  4.31664705e-01,  7.68714771e-02],
        [-6.53394908e-02,  2.25880206e-01,  6.69758201e-01, ...,
         -4.13879871e-01,  5.39322942e

In [155]:
# save_file(result_s,path_s)

### 6 flatten

In [156]:
p_faltten=torch.flatten(pixel,start_dim=0, end_dim=-1)
p_faltten

tensor([-0.1747,  0.4304,  1.4762,  ..., -1.4211, -0.3267, -1.5836])

In [157]:
p_faltten.shape

torch.Size([3072])

In [158]:
def Flatten(X):
    result=[]
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
                result.extend((X[i,j].numpy()))

    return result

In [159]:
s_faltten=np.array(Flatten(pixel)).reshape(1,-1)

In [160]:
s_faltten

array([[-0.17467964,  0.43038133,  1.4762458 , ..., -1.4210529 ,
        -0.32666624, -1.5835963 ]], dtype=float32)

In [161]:
result_p["flatten"]=np.array([p_faltten.detach().numpy()])
result_s["flatten"]=s_faltten

In [162]:
# save_file(result_s,path_s)

### 7 sigmoid

In [163]:
p_sigmoid=torch.sigmoid(pixel)
p_sigmoid

tensor([[[0.4564, 0.6060, 0.8140,  ..., 0.1995, 0.7079, 0.3630],
         [0.4398, 0.3562, 0.8123,  ..., 0.2298, 0.5145, 0.2662],
         [0.5781, 0.4466, 0.6011,  ..., 0.3186, 0.6732, 0.2807],
         ...,
         [0.4301, 0.4889, 0.6996,  ..., 0.4168, 0.4602, 0.4559],
         [0.6235, 0.5676, 0.3504,  ..., 0.3535, 0.1881, 0.5530],
         [0.5469, 0.6041, 0.7491,  ..., 0.0688, 0.6216, 0.3344]],

        [[0.4933, 0.7125, 0.5153,  ..., 0.7312, 0.2269, 0.6863],
         [0.7754, 0.2908, 0.2796,  ..., 0.4595, 0.2526, 0.3219],
         [0.6341, 0.6109, 0.2184,  ..., 0.6231, 0.5800, 0.5963],
         ...,
         [0.6292, 0.1704, 0.6531,  ..., 0.1559, 0.4680, 0.6728],
         [0.7182, 0.7559, 0.8855,  ..., 0.4164, 0.6431, 0.1250],
         [0.3570, 0.8624, 0.2783,  ..., 0.7259, 0.2891, 0.6054]],

        [[0.5493, 0.6339, 0.6287,  ..., 0.2737, 0.2120, 0.7356],
         [0.6529, 0.5105, 0.5656,  ..., 0.1684, 0.3618, 0.2859],
         [0.2818, 0.7681, 0.5642,  ..., 0.5208, 0.3154, 0.

In [164]:
result_p["sigmoid"]=p_sigmoid.detach().numpy()

In [165]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

In [166]:
sigmoid(pixel).detach().numpy()

array([[[0.4564408 , 0.6059647 , 0.81400484, ..., 0.19953336,
         0.7079151 , 0.36304688],
        [0.43977067, 0.3562329 , 0.81229645, ..., 0.22979164,
         0.5145122 , 0.26615444],
        [0.5781495 , 0.44655743, 0.6011063 , ..., 0.31861675,
         0.67316014, 0.28067634],
        ...,
        [0.43007687, 0.48889294, 0.6995966 , ..., 0.41684994,
         0.46015382, 0.4559053 ],
        [0.6235469 , 0.5676128 , 0.35040188, ..., 0.35351932,
         0.18806963, 0.5530287 ],
        [0.5468606 , 0.6041426 , 0.74910253, ..., 0.06881341,
         0.6216439 , 0.33444124]],

       [[0.49329674, 0.71245825, 0.5152674 , ..., 0.7312355 ,
         0.22685798, 0.68632555],
        [0.7753827 , 0.29083562, 0.2796144 , ..., 0.4595495 ,
         0.25262174, 0.32188293],
        [0.63410556, 0.610863  , 0.21837094, ..., 0.6231056 ,
         0.58001184, 0.596316  ],
        ...,
        [0.62918603, 0.17044634, 0.65305036, ..., 0.15587242,
         0.4679929 , 0.6728016 ],
        [0.7

In [167]:
result_s["sigmoid"]=sigmoid(pixel).detach().numpy()

In [168]:
# save_file(result_s,path_s)

### 8 roi_pool

In [169]:
import torchvision

In [170]:
inp=pixel.view(-1,3,32,32)
box=torch.tensor([[0,0,0,20,20]]).float()
p_roi=torchvision.ops.roi_pool(inp,box,output_size=(6,6))
p_roi

tensor([[[[1.4762, 1.0790, 1.9505, 1.4595, 1.8063, 2.0017],
          [1.5666, 2.1321, 2.4177, 3.0786, 1.8063, 1.8063],
          [1.4567, 2.6301, 0.9331, 1.5528, 1.6583, 1.6604],
          [1.3379, 1.2830, 0.9434, 2.1661, 1.2909, 1.1808],
          [1.5318, 1.7083, 2.0195, 1.3780, 1.6678, 1.6625],
          [1.1956, 1.7083, 2.0195, 1.7955, 1.8130, 1.2911]],

         [[1.2390, 1.9214, 1.8987, 2.0583, 1.6551, 1.3550],
          [0.7458, 1.9214, 0.8632, 1.4835, 1.8839, 1.3456],
          [2.3608, 1.3933, 0.8929, 1.2317, 1.0333, 1.4060],
          [0.8848, 1.3933, 0.8929, 1.2961, 3.1148, 2.7379],
          [1.0759, 1.2432, 1.3230, 1.9307, 1.3471, 1.5990],
          [1.8013, 2.5237, 1.2565, 1.7346, 3.3328, 1.8135]],

         [[1.2343, 1.5939, 1.6645, 2.0071, 1.1097, 0.9190],
          [1.5870, 1.1289, 1.9778, 1.6035, 1.3395, 1.3395],
          [1.7974, 1.3209, 1.4649, 1.9555, 1.7001, 1.7001],
          [3.1985, 3.1985, 1.5745, 1.5745, 1.7001, 1.7001],
          [0.9126, 0.9897, 1.5933, 2

In [171]:
p_roi=p_roi.squeeze()

In [172]:
p_roi.numpy().shape

(3, 6, 6)

In [173]:
p_roi[0]

tensor([[1.4762, 1.0790, 1.9505, 1.4595, 1.8063, 2.0017],
        [1.5666, 2.1321, 2.4177, 3.0786, 1.8063, 1.8063],
        [1.4567, 2.6301, 0.9331, 1.5528, 1.6583, 1.6604],
        [1.3379, 1.2830, 0.9434, 2.1661, 1.2909, 1.1808],
        [1.5318, 1.7083, 2.0195, 1.3780, 1.6678, 1.6625],
        [1.1956, 1.7083, 2.0195, 1.7955, 1.8130, 1.2911]])

In [174]:
import torch
rois_in_feature = torch.Tensor([[0, 0, 3, 20, 31]])  #取4位小数

In [175]:
roi_start_w = 0
roi_start_h = 0
roi_end_w = 20
roi_end_h = 20

roi_width = (roi_end_w - roi_start_w + 1)
roi_height = (roi_end_h - roi_start_h + 1)

bin_size_w = roi_width / 6
bin_size_h = roi_height / 6

In [176]:
import math
_result=[]
for k in range(3):
    result_ = []
    for j in range(6):
        sub_res = []
        for i in range(6):
            result=pixel[..., int(roi_start_h+bin_size_h*(j)):math.ceil(roi_start_h+bin_size_h*(j+1)), int(roi_start_w+bin_size_w*(i)):math.ceil(roi_start_w+bin_size_w*(i+1))][k]
#             result=np.round(np.array(result.max()),4)
            sub_res.append(result.max())
        result_.append(sub_res)
    _result.append(result_)
result_[0]

[tensor(1.2343),
 tensor(1.5939),
 tensor(1.6645),
 tensor(2.0071),
 tensor(1.1097),
 tensor(0.9190)]

In [177]:
s_poi=np.array(_result)
s_poi[0]

array([[1.4762458 , 1.0790336 , 1.950539  , 1.4594734 , 1.8062773 ,
        2.0016794 ],
       [1.5666375 , 2.1321123 , 2.4176688 , 3.0786455 , 1.8062773 ,
        1.8062773 ],
       [1.4567353 , 2.6300526 , 0.93312246, 1.5528318 , 1.6582751 ,
        1.6603667 ],
       [1.337897  , 1.2829533 , 0.9434092 , 2.1661477 , 1.2909224 ,
        1.1807736 ],
       [1.5318081 , 1.7083447 , 2.019492  , 1.3780255 , 1.6677951 ,
        1.6625142 ],
       [1.195641  , 1.7083447 , 2.019492  , 1.7954652 , 1.8129898 ,
        1.2911074 ]], dtype=float32)

In [178]:
result_p["Roi_pool"]=p_roi.detach().numpy()

In [179]:
result_s["Roi_pool"]=s_poi

In [180]:
# save_file(result_s,path_s)

### 9 batch_norm

In [181]:
running_mean=torch.zeros(3)+0.001
running_var=torch.ones(3)*3
inp=pixel.view(-1,3,32,32)
p_batch_norm=torch.nn.functional.batch_norm(inp,running_mean,running_var,weight=None,bias=None,training=False,
                              momentum=0.1,eps=1e-05)

In [182]:
p_batch_norm

tensor([[[[-0.1014,  0.2479,  0.8517,  ..., -0.8026,  0.5105, -0.3251],
          [-0.1403, -0.3422,  0.8452,  ..., -0.6989,  0.0329, -0.5861],
          [ 0.1814, -0.1245,  0.2362,  ..., -0.4394,  0.4166, -0.5439],
          ...,
          [-0.1631, -0.0262,  0.4875,  ..., -0.1944, -0.0928, -0.1027],
          [ 0.2908,  0.1565, -0.3570,  ..., -0.3491, -0.8450,  0.1223],
          [ 0.1080,  0.2435,  0.6309,  ..., -1.5046,  0.2861, -0.3979]],

         [[-0.0161,  0.5233,  0.0347,  ...,  0.5773, -0.7085,  0.4515],
          [ 0.7147, -0.5152, -0.5470,  ..., -0.0942, -0.6268, -0.4308],
          [ 0.3169,  0.2598, -0.7368,  ...,  0.2897,  0.1858,  0.2247],
          ...,
          [ 0.3047, -0.9142,  0.3646,  ..., -0.9759, -0.0746,  0.4156],
          [ 0.5396,  0.6521,  1.1805,  ..., -0.1955,  0.3393, -1.1243],
          [-0.3402,  1.0590, -0.5506,  ...,  0.5616, -0.5201,  0.2464]],

         [[ 0.1136,  0.3164,  0.3035,  ..., -0.5639, -0.7586,  0.5903],
          [ 0.3642,  0.0237,  

In [183]:
result_p["norm"]=p_batch_norm.squeeze().detach().numpy()

In [184]:
def norm(X):
    eps=1e-05
    me=running_mean.view(3,1,1)
    var=running_var.view(3,1,1)
    return (X-me)/torch.sqrt(var+eps)

In [185]:
norm(pixel)

tensor([[[-0.1014,  0.2479,  0.8517,  ..., -0.8026,  0.5105, -0.3251],
         [-0.1403, -0.3422,  0.8452,  ..., -0.6989,  0.0329, -0.5861],
         [ 0.1814, -0.1245,  0.2362,  ..., -0.4394,  0.4166, -0.5439],
         ...,
         [-0.1631, -0.0262,  0.4875,  ..., -0.1944, -0.0928, -0.1027],
         [ 0.2908,  0.1565, -0.3570,  ..., -0.3491, -0.8450,  0.1223],
         [ 0.1080,  0.2435,  0.6309,  ..., -1.5046,  0.2861, -0.3979]],

        [[-0.0161,  0.5233,  0.0347,  ...,  0.5773, -0.7085,  0.4515],
         [ 0.7147, -0.5152, -0.5470,  ..., -0.0942, -0.6268, -0.4308],
         [ 0.3169,  0.2598, -0.7368,  ...,  0.2897,  0.1858,  0.2247],
         ...,
         [ 0.3047, -0.9142,  0.3646,  ..., -0.9759, -0.0746,  0.4156],
         [ 0.5396,  0.6521,  1.1805,  ..., -0.1955,  0.3393, -1.1243],
         [-0.3402,  1.0590, -0.5506,  ...,  0.5616, -0.5201,  0.2464]],

        [[ 0.1136,  0.3164,  0.3035,  ..., -0.5639, -0.7586,  0.5903],
         [ 0.3642,  0.0237,  0.1518,  ..., -0

In [186]:
result_s["norm"]=norm(pixel).detach().numpy()

In [187]:
# save_file(result_s,path_s)

### 10 cross_entropy

In [188]:
inp=pixel.view(-1,3,32,32)
target = torch.randint(3, (1,32,32), dtype=torch.int64)
p_cro_loss=torch.nn.functional.cross_entropy(inp, target, weight=None,
                                  size_average=None, ignore_index=-100, reduce=None,reduction='mean')

In [189]:
p_cro_loss

tensor(1.3748)

In [190]:
result_p["cross_entropy"]=np.array([p_cro_loss.detach().numpy()]).reshape(1,1)

In [191]:
result_p["cross_entropy"].reshape(1,1)

array([[1.3748418]], dtype=float32)

In [193]:
#inp,1,C,H,W, target: 1,H,W
class cross_entropy:
    def __init__(self,inp,target):
        self.inp=inp
        self.target=target
        self.H=target.shape[1]
        self.W=target.shape[2]
    def forward(self):
        return self.nn_loss(self.log_softmax())
    def log_softmax(self):
        exp=torch.exp(self.inp[0])
        sum_=torch.sum(exp,dim=0)
        soft_max=exp/sum_
        return torch.log(soft_max)
    def nn_loss(self,inp):
        loss=0
        for i in range(self.H):
            for j in range(self.W):
                index=target[0,i,j]
                num=inp[index,i,j]
                loss-=num
        return (loss)/self.H/self.W

In [194]:
cs=cross_entropy(inp,target)
cs.forward()

tensor(1.3748)

In [195]:
result_s["cross_entropy"]=np.array([cs.forward().detach().numpy()]).reshape(1,-1)

In [196]:
# save_file(result_s,path_s)

###  11 mse_loss

In [197]:
inp=pixel.view(-1,3,32,32)
target = torch.randn(1,3,32,32)
p_mse_loss=torch.nn.functional.mse_loss(inp, target, 
                                          size_average=None,reduce=None, reduction='mean')

In [198]:
p_mse_loss

tensor(1.9146)

In [199]:
result_p["mse_loss"]=np.array([p_mse_loss.detach().numpy()]).reshape(1,1)

In [200]:
def mse_loss(x,target):
    return np.mean((x.numpy()-target.numpy())**2)

In [201]:
mse_loss(pixel,target.view(3,32,32))

1.9146191

In [202]:
result_s["mse_loss"]=np.array([mse_loss(pixel,target.view(3,32,32))]).reshape(1,-1)

In [203]:
# save_file(result_s,path_s)

## save files

In [206]:
def save_file(List_file,path):
    with open(path,"w") as f:
        for k,v in List_file.items():
            f.write(k+': \n')
            for i in range(v.shape[0]):
                np.savetxt(f,List_file[k][i])
                f.write('\n')
            f.write('\n')
            f.write('_______________________'+'\n')
    f.close()

In [207]:
path_p='./torch_out'
path_s='./my_out'

In [208]:
save_file(result_p,path_p)

In [209]:
save_file(result_s,path_s)